name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - name: "Install Akamai"
        run: brew install akamai
        shell: bash  
    
