name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name : "Install Akamai"
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: akamai
          
    
