name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - name: "Install Brew"
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: bash
      
      - name: "Install Akamai"
        run: brew install akamai
        shell: bash  
    
